apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
        - image: us-west4-docker.pkg.dev/products-microservices-439002/image-registry/products-microservice
          name: products-microservice
          env:
            - name: PORT
              value: "3001"
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: DATABASE_URL
              value: "file:./dev.db"
          resources: {}
status: {}
