apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: us-west4-docker.pkg.dev/products-microservices-439002/image-registry/payments-microservice
          name: payments-microservice
          env:
            - name: PORT
              value: "3003"
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: STRIPE_SUCCESS_URL
              value: "http://localhost:3003/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://localhost:3003/payments/cancel"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_secret
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_endpoint_secret
          resources: {}
status: {}
